global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - alert.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['host.docker.internal:9093']
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name:  'node-exporter'
# Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 1s
  metrics_path: '/metrics'
  static_configs:
    - targets: ['host.docker.internal:9100'] # trocar por 172.17.0.1 se for executar em linux
      labels:
        group: 'production'
